export const universities = [
  {
    slug: "amity-university-online",
    name: "Amity University",
    logo: "/universities/Amity university 400x200.png",
    grade: "NAAC A+",
    fees: "₹1,99,000",
  },
  {
    slug: "acharya-nagarjuna-university-online",
    name: "Acharya Nagarjuna University",
    logo: "/universities/Acharya-Nagarjuna 400x200.png",
    grade: "NAAC A+",
    fees: "₹85,000",
  },
  {
    slug: "amrita-university-online",
    name: "Amrita University",
    logo: "/universities/Amrita 400x200.png",
    grade: "NAAC A++",
    fees: "₹1,70,000",
  },
  {
    slug: "jain-university-online",
    name: "Jain University",
    logo: "/universities/jain.png",
    grade: "NAAC A++",
    fees: "₹1,60,000",
  },
  {
    slug: "manipal-university-online",
    name: "Manipal University Jaipur",
    logo: "/universities/manipal.png",
    grade: "NAAC A+",
    fees: "₹1,75,000",
  },
  {
    slug: "chandigarh-university-online",
    name: "Chandigarh University",
    logo: "/universities/cu.png",
    grade: "NAAC A+",
    fees: "₹1,58,000",
  },
  {
    slug: "lpu-online",
    name: "LPU Online",
    logo: "/universities/lpu.png",
    grade: "NAAC A++",
    fees: "₹1,80,000",
  },
  {
    slug: "dy-patil-online",
    name: "DY Patil University",
    logo: "/universities/dypatil.png",
    grade: "NAAC A++",
    fees: "₹1,69,000",
  },
  {
    slug: "nmims-global",
    name: "NMIMS Global",
    logo: "/universities/nmims.png",
    grade: "NAAC A+",
    fees: "₹2,10,000",
  },
  {
    slug: "upes-online",
    name: "UPES Online",
    logo: "/universities/upes.png",
    grade: "NAAC A",
    fees: "₹1,50,000",
  },
  {
    slug: "sikkim-manipal-online",
    name: "Sikkim Manipal University",
    logo: "/universities/smu.png",
    grade: "NAAC A+",
    fees: "₹1,10,000",
  },
  {
    slug: "uttaranchal-university-online",
    name: "Uttaranchal University",
    logo: "/universities/uttaranchal.png",
    grade: "NAAC A+",
    fees: "₹95,000",
  },
  {
    slug: "shoolini-university-online",
    name: "Shoolini University",
    logo: "/universities/shoolini.png",
    grade: "NAAC A+",
    fees: "₹1,20,000",
  },
  {
    slug: "vivekananda-global-university",
    name: "VGU Online",
    logo: "/universities/vgu.png",
    grade: "NAAC A+",
    fees: "₹1,15,000",
  },
  {
    slug: "bharathidasan-university",
    name: "Bharathidasan University",
    logo: "/universities/bdu.png",
    grade: "NAAC A+",
    fees: "₹80,000",
  },
  {
    slug: "ignou-mba",
    name: "IGNOU",
    logo: "/universities/ignou.png",
    grade: "NAAC A++",
    fees: "₹62,000",
  },
  {
    slug: "dr-mgr-university",
    name: "Dr. MGR University",
    logo: "/universities/mgr.png",
    grade: "NAAC A+",
    fees: "₹95,000",
  },
  {
    slug: "alagappa-university",
    name: "Alagappa University",
    logo: "/universities/alagappa.png",
    grade: "NAAC A+",
    fees: "₹78,000",
  },
  {
    slug: "kurukshetra-university",
    name: "Kurukshetra University",
    logo: "/universities/kurukshetra.png",
    grade: "NAAC A+",
    fees: "₹89,000",
  },
  {
    slug: "andhra-university",
    name: "Andhra University",
    logo: "/universities/andhra.png",
    grade: "NAAC A+",
    fees: "₹92,000",
  },
  {
    slug: "maharishi-markandeshwar-university",
    name: "MMU Online",
    logo: "/universities/mmu.png",
    grade: "NAAC A++",
    fees: "₹1,25,000",
  },
];